# Generated by Django 5.0.7 on 2024-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Film_name', max_length=50, verbose_name='Название')),
                ('short_description', models.CharField(max_length=300, verbose_name='Описание фильма')),
                ('text', models.TextField(verbose_name='Отзыв о фильме')),
            ],
            options={
                'verbose_name': 'Отзыв о фильме',
                'verbose_name_plural': 'Отзывы о фильмах',
            },
        ),
    ]
